// app/layout.tsx (or pages/_app.tsx if using pages directory)
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { UsersRound } from 'lucide-react';

import "./globals.css";

// Import Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100","200","300","400","500","600","700","800","900"], // optional all weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <div className="flex flex-col items-center mt-14 justify-center">
          {/* Heading */}
          <h1 className="text-6xl" style={{ fontFamily: 'var(--font-poppins)' }}>
            BOO BOO
          </h1>

          {/* Navigation */}
          <nav className="flex mt-6 gap-20 text-xl" style={{ fontFamily: 'var(--font-poppins)' }}>
            <a href="">Home</a>
            <a href="">Our Story</a>
            <a href="">Menu</a>
            <a href="">Activities</a>
            <UsersRound />
          </nav>

          {/* Children content */}
          <div className="mt-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
